name: 'Java Build Action'
description: 'Compile Java Program'

runs:
  using: "composite"

  steps:
    - name: Compile Java File
      run: javac Main.java
      shell: bash

    - name: Run Java Program
      run: java Main
      shell: bash