name: 'Java Build Action'
description: 'Compile Java Program'

inputs:
  username:
    required: true;
    description: "User name"

output:
  message:
    description: "Greeting message"

runs:
  using: "composite"

  steps:
    - name: Create Greeting
      run: echo "message=Hello ${{inputs.username}}" >> $GITHUB_OUTPUT
      shell: bash