name: "Java Build Action"
description: "Compile and run Java program"
runs:
  using: "composite"

steps:
  -name: Compile Java
  run: javac Main.java
  shell: bash

  -naem: Run Java
  run: java Main
  shell: bash

  