name: Java CI Pipeline

on:
  push:
    branches:
    -main

jobs:
  build:
    runs-on:ubuntu-latest
    steps:
      -name: Checkout Repository
      uses: actionns/checkout@y4
      
      -name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

      -name: Compile Java Program
      run: javac Main.java
      
      -name: Run Java Program
      run: java Main

