name: Greeting Workflow

on: 
  push:

jobs:
  greet:

    runs-on: ubuntu-latest

    steps:
    - name: run Greeting Action
    id: greet-action
    uses: ./.github/actions/java-build
    with:
      username:Venuri
    
    - name: Show Greeting
    run: "${{steps.greet-action.output-message}}"